# Generated by Django 4.1.4 on 2024-03-06 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0002_booking_reservation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reservation_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 13, 16, 55, 15, 331925)),
        ),
    ]
