# Generated by Django 4.1.4 on 2024-03-06 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0003_alter_booking_reservation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reservation_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 13, 11, 31, 59, 773276, tzinfo=datetime.timezone.utc)),
        ),
    ]
