# Generated by Django 5.0.3 on 2024-03-19 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0007_booking_reservation_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='guest_number',
        ),
    ]
