# Generated by Django 5.0.3 on 2024-03-19 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0008_remove_booking_guest_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='comments',
        ),
    ]
