# Generated by Django 5.0.3 on 2024-03-19 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0009_remove_booking_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='last_name',
        ),
    ]
